---
  swagger: "2.0"
  info:
    title: "Dream Commands API"
    description: "Share useful commands"
    version: "1.0.0"
  schemes:
    - "http"
    - "https"
  basePath: "/api"
  consumes:
    - application/json
  produces:
    - application/json